const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Raises the iOS deployment target of every CocoaPods target to the project minimum.
 *
 * CocoaPods gives resource-bundle targets the deployment target declared in their own
 * podspec rather than the one from the Podfile's `platform :ios` line. A few pods still
 * ship 12.x/13.x there (AsyncStorage's resource bundle, RNSVG's filters), and recent
 * Xcode refuses to build anything below iOS 15, so the build dies with:
 *
 *   The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 13.0,
 *   but the range of supported deployment target versions is 15.0 to 27.0.x.
 *
 * `react_native_post_install` doesn't cover these targets, so we patch the generated
 * Podfile's post_install block ourselves. This runs as a config plugin rather than a
 * hand edit because ios/ is gitignored and regenerated by every prebuild.
 */

const MARKER = '# expo-config-plugin: raise pod deployment targets';
const ANCHOR = 'react_native_post_install(';

function buildSnippet(minimum) {
  return `

    ${MARKER}
    # Runs after react_native_post_install so it has the last word on these settings.
    # Resource-bundle targets inherit their podspec's deployment target, not the
    # Podfile's platform, and Xcode rejects anything below iOS 15. Raise the stragglers.
    installer.pods_project.targets.each do |pod_target|
      pod_target.build_configurations.each do |pod_config|
        existing = pod_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if existing.nil? || existing.to_f < ${minimum}
          pod_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '${minimum}'
        end
      end
    end`;
}

/** Returns the index just past the closing paren of the call starting at `openIndex`. */
function endOfCall(contents, openIndex) {
  let depth = 0;
  for (let i = openIndex; i < contents.length; i += 1) {
    const char = contents[i];
    if (char === '(') depth += 1;
    else if (char === ')') {
      depth -= 1;
      if (depth === 0) return i + 1;
    }
  }
  return -1;
}

/**
 * @param {import('expo/config').ExpoConfig} config
 * @param {{ minimum?: string }} [props]
 */
module.exports = function withPodDeploymentTarget(config, props = {}) {
  const minimum = props.minimum ?? '16.4';

  return withDangerousMod(config, [
    'ios',
    async (modConfig) => {
      const podfilePath = path.join(modConfig.modRequest.platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfilePath, 'utf8');

      // Prebuild can run repeatedly against an existing ios/ directory.
      if (contents.includes(MARKER)) return modConfig;

      const anchorIndex = contents.indexOf(ANCHOR);
      if (anchorIndex === -1) {
        throw new Error(
          `withPodDeploymentTarget: could not find "${ANCHOR}" in the generated Podfile. ` +
            'The Expo template probably changed — update this plugin rather than editing ios/Podfile, ' +
            'which is regenerated on every prebuild.'
        );
      }

      const insertAt = endOfCall(contents, anchorIndex + ANCHOR.length - 1);
      if (insertAt === -1) {
        throw new Error(
          'withPodDeploymentTarget: the react_native_post_install(...) call in the generated Podfile ' +
            'has unbalanced parentheses, so there is nowhere safe to append. Update this plugin.'
        );
      }

      const patched = contents.slice(0, insertAt) + buildSnippet(minimum) + contents.slice(insertAt);
      fs.writeFileSync(podfilePath, patched);

      return modConfig;
    },
  ]);
};
